trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
 - stage: Build
   jobs:
   - job: BuildJob
     steps:
     - script: npm install
       displayName: 'Installing Dependencies'

     - script: npm run build
       displayName: 'Running Build'

     - task: PublishBuildArtifacts@1
       inputs: 
         pathtoPublish: '$(Build.ArtifactStagingDirectory)'
         artifactName: 'drop'
         publishLocation: 'Container'
       displayName: 'Publish Artifacts'
