trigger:
  branches:
    include:
      -main

pool:
  vmImage:'ubuntu-latest'

stages:
 - stage: Build
   jobs
   -job: BuildJob
    steps:
   - script: 
      npm install
      displayName: 'Installing Dependencies'

   - script:
     npm run build
     displayName: 'Running Build'

   - task: PulishBuildArtifacts@1
     inputs: 
     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
     artifactName: 'drop'
     publishLocation: 'Container'
     displaName: 'Publish Artifacts' 